steps:
# Step 1: Install frontend dependencies
# This navigates into your 'frontend' directory and runs 'npm install'.
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'frontend'

# Step 2: Build the static website
# This runs the 'build' script defined in your frontend's package.json.
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'frontend'

# Step 3: Deploy to Google Cloud Storage
# This copies the contents of your 'frontend/build' directory to your storage bucket,
# making it a live website. The '-m' flag performs a parallel copy for speed,
# and 'rsync' efficiently syncs only the changed files.
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-r', 'frontend/build', 'gs://bhramannfrontend'] # <-- CHANGE THIS
